service: ocaml-serverless-example

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: eu-central-1

plugins:
  - serverless-offline

#this is actually needed not to include the whole bucklesript toolchain in deployment zip
package:
  exclude:
    - lib/bs/**
    - node_modules/bs-platform/**
  include:
    - node_modules/bs-platform/lib/js/**
    - lib/js/**

functions:
  some:
    handler: lib/js/src/index.some_function
    events:
      - http:
          path: /
          method: get
          cors: true

  fact:
    handler: lib/js/src/index.factorial_function
    events:
      - http:
          path: factorial/{num}
          method: get
          cors: true


